import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-5 py-2 flex justify-between gap-5 ">
          <div>
            <img src="/logo.jpg" className="w-13 rounded-full h-10" alt="" />
          </div>
          <div className="flex gap-6">
            <Link href="/foods" className="btn">
              Food
            </Link>
            <Link href="/reviews" className="btn">
              Review
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
